clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  build:
    image: gcr.io/time-coin/sbt:latest
    commands:
      - git clone https://github.com/mytimecoin/scala-abci-server.git scala-abci-server --depth 1
      - git clone https://github.com/mytimecoin/timechain.git timechain --depth 1
      - cd /workdir/code/scala-abci-server && sbt publishLocal
      - cd /workdir/code/timechain && sbt test
branches: ci
