clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  tests:
    image: gcr.io/time-coin/sbt:latest
    commands:
      - git clone https://github.com/mytimecoin/scala-abci-server.git scala-abci-server --depth 1
      - cd /workdir/code/scala-abci-server && sbt publishLocal
      - cd /workdir/code && sbt test
      - cd /workdir/code && sbt scalafmtCheck
      - cd /workdir/code && sbt scalafixTest
