clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  tests:
    image: gcr.io/time-coin/builder-java-sbt:0.1
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/ivy-cache:/workdir/ivy
    commands:
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 test scalafmtCheck scalafixTest
  package:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/ivy-cache:/workdir/ivy
    commands:
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 cli/universal:packageBin
    when:
      event: tag
  github_release:
    image: plugins/github-release
    files:
      - /workdir/code/cli/target/universal/*.zip
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
