clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  tests:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export COURSIER_CACHE='/workdir/coursier/'
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - git clone https://github.com/mytimecoin/scala-abci-server.git scala-abci-server --depth 1
      - cd /workdir/code/scala-abci-server && sbt $SBT_OPTS publishLocal
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 scalafmtCheck scalafixTest test
  package:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/'
      - export COURSIER_CACHE='/workdir/coursier/'
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 cli/universal:packageBin
    when:
      event: tag
  release:
    image: plugins/github-release
    files:
      - /workdir/code/cli/target/universal/*.zip
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
